<?php

/**
 * Created by PhpStorm.
 * User: tangui
 * Date: 28/02/17
 * Time: 13:55
 */
namespace OC\PlatformBundle\Validator;

use Symfony\Component\Validator\Constraint;

/**
 * Class Antiflood
 * @package OC\PlatformBundle\Validator
 * @Annotation
 */
class Antiflood extends Constraint
{
    public $message = "Voous avez déjà postez un message il y a moins de 15 secondes, veuillez attendre un peu.";

    public function validatedBy()
    {
        return 'oc_platform_antiflood'; // TODO: Change the autogenerated stub
    }

}